In [1]:
import numpy as np

In [2]:
n = np.sqrt(8)
np.abs((n-1)/(n+1))**2

0.22809435732932976

In [1]:
from pytmatrix import tmatrix_aux
from pytmatrix import tmatrix
from pytmatrix import refractive
import numpy as np

In [5]:
refractive.mg_refractive((2, 8-1j), (1-0.1, 0.1))

(2.2581306052199412-0.011476131284860767j)

In [11]:
scatterer = tmatrix.Scatterer(radius=0.126, wavelength=1.0, m=1.72+0.02j, axis_ratio=1, shape=-1)
scatterer.get_SZ()

(array([[ 2.67108759e-02+4.90350508e-03j,  1.83074548e-25+3.17410621e-26j],
        [-1.83074548e-25-3.17410621e-26j, -2.67108759e-02-4.90350508e-03j]]),
 array([[ 7.37515252e-04,  4.01154804e-18, -1.00914480e-26,
         -1.79366203e-43],
        [ 4.01154804e-18,  7.37515252e-04, -2.72636629e-41,
         -9.97508184e-29],
        [ 1.00914480e-26,  2.72636629e-41, -7.37515252e-04,
          2.71050543e-20],
        [-1.79366203e-43, -9.97508184e-29, -2.71050543e-20,
         -7.37515252e-04]]))

In [12]:
np.divide(0, 0, where)

C:\Users\zhaofei\AppData\Local\Temp\ipykernel_16088\2105560962.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(0, 0)


nan

In [6]:
scatterer.get_SZ()

(array([[ 2.67108759e-02+4.90350508e-03j,  1.83074548e-25+3.17410621e-26j],
        [-1.83074548e-25-3.17410621e-26j, -2.67108759e-02-4.90350508e-03j]]),
 array([[ 7.37515252e-04,  4.01154804e-18, -1.00914480e-26,
         -1.79366203e-43],
        [ 4.01154804e-18,  7.37515252e-04, -2.72636629e-41,
         -9.97508184e-29],
        [ 1.00914480e-26,  2.72636629e-41, -7.37515252e-04,
          2.71050543e-20],
        [-1.79366203e-43, -9.97508184e-29, -2.71050543e-20,
         -7.37515252e-04]]))

In [3]:
tmatrix.Scatterer.SHAPE_CYLINDER

-2

In [2]:
tmatrix_aux.VERSION

'0.3.2'

In [3]:
tmatrix_aux.geom_horiz_back

(90.0, 90.0, 0.0, 180.0, 0.0, 0.0)

In [4]:
tmatrix_aux.geom_horiz_forw

(90.0, 90.0, 0.0, 0.0, 0.0, 0.0)

In [5]:
from pytmatrix.test import test_tmatrix

In [6]:
test_tmatrix.run_tests()

test_adaptive_orient (pytmatrix.test.test_tmatrix.TMatrixTests)
Test an adaptive orientation averaging case ... ok
test_against_mie (pytmatrix.test.test_tmatrix.TMatrixTests)
Test scattering parameters against Mie results ... ok
test_asymmetry (pytmatrix.test.test_tmatrix.TMatrixTests)
Test calculation of the asymmetry parameter ... ok
test_fixed_orient (pytmatrix.test.test_tmatrix.TMatrixTests)
Test a fixed-point orientation averaging case ... ok
test_integrated_x_sca (pytmatrix.test.test_tmatrix.TMatrixTests)
Test Rayleigh scattering cross section integrated over sizes. ... ok
test_optical_theorem (pytmatrix.test.test_tmatrix.TMatrixTests)
Optical theorem: test that for a lossless particle, Csca=Cext ... ok
test_psd (pytmatrix.test.test_tmatrix.TMatrixTests)
Test a case that integrates over a particle size distribution ... ok
test_radar (pytmatrix.test.test_tmatrix.TMatrixTests)
Test that the radar properties are computed correctly ... ok
test_rayleigh (pytmatrix.test.test_tmatrix.TM

In [2]:
tmatrix_aux.geom_horiz_back

(90.0, 90.0, 0.0, 180.0, 0.0, 0.0)

In [4]:
(tmatrix_aux.geom_horiz_back,)

((90.0, 90.0, 0.0, 180.0, 0.0, 0.0),)

In [5]:
import numpy as np

In [6]:
Q = np.array([[1, 1, 0, 0],
    [1, -1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, -1]])
np.linalg.inv(Q)

array([[ 0.5,  0.5,  0. ,  0. ],
       [ 0.5, -0.5, -0. , -0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [-0. , -0. , -0. , -1. ]])

In [10]:
Q = np.array([[1., 1, 0, 0],
                [1, -1, 0, 0],
                [0, 0, 1, 0],
                [0, 0, 0, -1]])
invQ = np.array([[0.5,  0.5,  0.,  0.],
                    [0.5, -0.5, -0., -0.],
                    [0.,  0.,  1.,  0.],
                    [-0., -0., -0., -1.]])
Q@invQ

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
tmatrix_aux.geom_horiz_forw

(90.0, 90.0, 0.0, 0.0, 0.0, 0.0)

In [6]:
2/(5-0.2j)

(0.3993610223642173+0.01597444089456869j)