In [39]:
# 比较TmatrixScatter和MieSphere的散射性质，验证两者的一致性
import sys
sys.path.append(r"E:\zhaofei\exps\project\lunar_scattering\lunar_regolith_scattering\mores")

In [40]:
import numpy as np

In [41]:
f = 2.38e9
thickness = 1.0
epsr_background = 2.7 - 0.002j
epsr_particle = 6.0 - 0.2j
wavelength = 3e8 / f
fs = 0.001

# Default and derived
D = 0.1*wavelength
radius = D * 0.5
geometric_cross_section = np.pi * radius**2
Dmax = D

In [42]:
from mores.layer.MieSphere import MieSphere
from mores.layer.TmatrixScatterer import TmatrixScatterer
from mores.misc.lunar_rocks_psd import LunarRocksPSD

In [43]:
psd_obj = LunarRocksPSD(k=fs)
particle_size = (0, Dmax, psd_obj.lunar_psd_vol)

In [44]:
miesphere_layer = MieSphere(f=f, thickness=thickness, epsr_background=epsr_background, epsr_particle=epsr_particle, 
                            particle_size=particle_size, num_points=100)

In [45]:
tmatrix_layer = TmatrixScatterer(f=f, thickness=thickness, epsr_background=epsr_background, epsr_particle=epsr_particle, particle_size=particle_size, particle_shape=(1.0, 'SPHEROID'))

In [46]:
miesphere_layer.n0

0

In [47]:
tmatrix_layer.n0

2555079.5619427226

In [36]:
miesphere_layer.extinction_matrix()

array([[0.0372186, 0.       , 0.       , 0.       ],
       [0.       , 0.0372186, 0.       , 0.       ],
       [0.       , 0.       , 0.0372186, 0.       ],
       [0.       , 0.       , 0.       , 0.0372186]])

In [23]:
tmatrix_layer.extinction_matrix((0,0))

array([[ 1.10553322e-03,  0.00000000e+00,  6.37029693e-21,
        -1.23404122e-19],
       [ 0.00000000e+00,  1.10553322e-03,  8.37649385e-21,
         1.71249191e-19],
       [ 1.67529877e-20,  1.27405939e-20,  1.10553322e-03,
         0.00000000e+00],
       [ 3.42498382e-19, -2.46808244e-19, -0.00000000e+00,
         1.10553322e-03]])

In [52]:
# tmatrix_layer.extinction_matrix((45,0))

In [53]:
miesphere_layer.phase_matrix((20, 180, 45, 0))

array([[ 0.00156651,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.00273992,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00188031,  0.00043404],
       [ 0.        ,  0.        , -0.00043404,  0.00188031]])

In [54]:
miesphere_layer.phase_matrix((45, 180, 45, 0))

array([[ 4.29662249e-04,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.22421953e-03,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  4.28740621e-04,
         6.15254421e-05],
       [ 0.00000000e+00,  0.00000000e+00, -6.15254421e-05,
         4.28740621e-04]])

In [49]:
tmatrix_layer.phase_matrix((10, 180, 45, 0))

Calculating phase matrix for multi-sized particles, which may take some time...


array([[ 1.33374960e-09,  8.47032947e-20,  1.00320926e-14,
        -4.01501899e-16],
       [ 8.47032947e-20,  1.68286769e-05, -1.19990506e-12,
         4.01501900e-16],
       [-2.00641851e-14,  2.39981012e-12,  1.40541450e-07,
        -5.67809373e-09],
       [-8.03003798e-16,  8.03003799e-16,  5.67809373e-09,
         1.40541450e-07]])

In [48]:
tmatrix_layer.phase_matrix((45, 180, 45, 0))

Calculating phase matrix for multi-sized particles, which may take some time...


array([[ 1.33374960e-09,  8.47032947e-20,  1.00320926e-14,
         4.01501899e-16],
       [ 8.47032947e-20,  1.68286769e-05, -1.19990506e-12,
        -4.01501900e-16],
       [-2.00641851e-14,  2.39981012e-12,  1.40541450e-07,
         5.67809373e-09],
       [ 8.03003798e-16, -8.03003799e-16, -5.67809373e-09,
         1.40541450e-07]])

In [26]:
tmatrix_layer.phase_matrix((45, 180, 45, 0))

Calculating phase matrix for multi-sized particles, which may take some time...


array([[ 1.82613974e-05,  0.00000000e+00, -1.35934197e-22,
         6.44895543e-24],
       [ 0.00000000e+00,  1.82613974e-05, -2.39901543e-22,
        -3.92056272e-24],
       [-4.79803085e-22, -2.71868394e-22,  1.82613974e-05,
         1.35032393e-23],
       [-7.84112544e-24,  1.28979109e-23, -1.35032393e-23,
         1.82613974e-05]])

In [58]:
tmatrix_layer.phase_matrix((20, 180, 45, 0))

Calculating phase matrix for multi-sized particles, which may take some time...


array([[ 1.82613974e-05,  0.00000000e+00,  9.96736096e-23,
        -7.19410330e-27],
       [ 0.00000000e+00,  1.82613974e-05,  3.99461333e-23,
         9.00317449e-25],
       [ 7.98922666e-23,  1.99347219e-22,  1.82613974e-05,
        -4.68225795e-24],
       [ 1.80063490e-24, -1.43882066e-26,  4.68225795e-24,
         1.82613974e-05]])

In [59]:
tmatrix_layer.phase_matrix((20, 180, 45, 0))

Calculating phase matrix for multi-sized particles, which may take some time...


array([[ 1.82613974e-05,  0.00000000e+00,  9.96736096e-23,
         7.19410330e-27],
       [ 0.00000000e+00,  1.82613974e-05,  3.99461333e-23,
        -9.00317449e-25],
       [ 7.98922666e-23,  1.99347219e-22,  1.82613974e-05,
         4.68225795e-24],
       [-1.80063490e-24,  1.43882066e-26, -4.68225795e-24,
         1.82613974e-05]])

In [61]:
tmatrix_layer.phase_matrix((60, 180, 30, 0))

Calculating phase matrix for multi-sized particles, which may take some time...


array([[ 1.82613974e-05,  0.00000000e+00,  9.96736096e-23,
         7.19410330e-27],
       [ 0.00000000e+00,  1.82613974e-05,  3.99461333e-23,
        -9.00317449e-25],
       [ 7.98922666e-23,  1.99347219e-22,  1.82613974e-05,
         4.68225795e-24],
       [-1.80063490e-24,  1.43882066e-26, -4.68225795e-24,
         1.82613974e-05]])

In [62]:
tmatrix_layer.phase_matrix((20, 180, 30, 0))

Calculating phase matrix for multi-sized particles, which may take some time...


array([[ 1.82613974e-05,  0.00000000e+00,  9.96736096e-23,
        -7.19410330e-27],
       [ 0.00000000e+00,  1.82613974e-05,  3.99461333e-23,
         9.00317449e-25],
       [ 7.98922666e-23,  1.99347219e-22,  1.82613974e-05,
        -4.68225795e-24],
       [ 1.80063490e-24, -1.43882066e-26,  4.68225795e-24,
         1.82613974e-05]])