In [1]:
# 比较TmatrixScatter和MieSphere的散射性质，验证两者的一致性
import sys
sys.path.append(r"E:\zhaofei\exps\project\lunar_scattering\lunar_regolith_scattering\mores")

In [2]:
import numpy as np

In [3]:
f = 2.38e9
thickness = 1.0
epsr_background = 2.7 - 0.002j
epsr_particle = 6.0 - 0.2j
wavelength = 3e8 / f
fs = 0.001

# Default and derived
D = 0.1*wavelength
radius = D * 0.5
geometric_cross_section = np.pi * radius**2
particle_size = (radius, fs)

In [4]:
from mores.layer.MieSphere import MieSphere
from mores.layer.TmatrixScatterer import TmatrixScatterer

In [5]:
miesphere_layer = MieSphere(f=f, thickness=thickness, epsr_background=epsr_background, epsr_particle=epsr_particle, particle_size=particle_size)

In [6]:
miesphere_layer.n0

953.6049235406055

In [7]:
tmatrix_layer = TmatrixScatterer(f=f, thickness=thickness, epsr_background=epsr_background, epsr_particle=epsr_particle, particle_size=particle_size)

In [8]:
tmatrix_layer.n0

953.6049235406055

In [9]:
miesphere_layer.extinction_matrix()

array([[0.00540115, 0.        , 0.        , 0.        ],
       [0.        , 0.00540115, 0.        , 0.        ],
       [0.        , 0.        , 0.00540115, 0.        ],
       [0.        , 0.        , 0.        , 0.00540115]])

In [10]:
tmatrix_layer.extinction_matrix((0,0))

array([[ 5.32367517e-03,  0.00000000e+00,  4.24008435e-20,
        -3.87858400e-19],
       [ 0.00000000e+00,  5.32367517e-03,  5.57615613e-20,
         4.52498927e-19],
       [ 1.11523123e-19,  8.48016870e-20,  5.32367517e-03,
         0.00000000e+00],
       [ 9.04997854e-19, -7.75716800e-19, -0.00000000e+00,
         5.32367517e-03]])

In [11]:
tmatrix_layer.extinction_matrix((45,0))

array([[ 5.32367517e-03,  0.00000000e+00, -6.09975291e-20,
        -1.68212463e-19],
       [ 0.00000000e+00,  5.32367517e-03, -6.54270970e-20,
         5.86319437e-19],
       [-1.30854194e-19, -1.21995058e-19,  5.32367517e-03,
        -8.51083349e-18],
       [ 1.17263887e-18, -3.36424927e-19,  8.51083349e-18,
         5.32367517e-03]])

In [12]:
miesphere_layer.phase_matrix((45, 180, 45, 0))

array([[ 3.72573468e-08,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  2.27539561e-04,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.90995709e-06,
         9.83365347e-08],
       [ 0.00000000e+00,  0.00000000e+00, -9.83365347e-08,
         2.90995709e-06]])

In [16]:
miesphere_layer.phase_matrix((30, 180, 30, 0))

array([[ 6.27988688e-05,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  2.41990359e-04,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.23274956e-04,
         7.81045057e-08],
       [ 0.00000000e+00,  0.00000000e+00, -7.81045057e-08,
         1.23274956e-04]])

In [13]:
tmatrix_layer.phase_matrix((45, 180, 45, 0))

array([[ 3.72505262e-08,  1.18636047e-18,  2.08385869e-13,
         6.68612252e-15],
       [ 1.21160218e-18,  2.27532480e-04, -1.62947295e-11,
        -6.68612251e-15],
       [-4.16771738e-13,  3.25894589e-11,  2.90977040e-06,
         9.45560420e-08],
       [ 1.33722451e-14, -1.33722454e-14, -9.45560420e-08,
         2.90977040e-06]])

In [15]:
tmatrix_layer.phase_matrix((30, 180, 30, 0))

array([[ 6.27967479e-05,  1.88050756e-18,  1.07426198e-11,
         4.33921901e-15],
       [ 1.89312841e-18,  2.41982502e-04, -2.10879148e-11,
        -4.33921898e-15],
       [-2.14852397e-11,  4.21758296e-11,  1.23270875e-04,
         7.51574736e-08],
       [ 8.67843808e-15, -8.67843807e-15, -7.51574736e-08,
         1.23270875e-04]])