In [1]:
import numpy as np

In [3]:
# S = np.array([[2+1j, 1+3j], [3-4j, 5-0.5j]])
S = np.array([[2+1j, 0], [0, 2+1j]])
Ke = np.array([[2*np.imag(S[0, 0]), 0, np.imag(S[0, 1]), -np.real(S[0, 1])],
                [0, 2*np.imag(S[1, 1]), np.imag(S[1, 0]), np.real(S[1, 0])],
                [2*np.imag(S[1, 0]), 2*np.imag(S[0, 1]), np.imag(S[0, 0]+S[1, 1]), np.real(S[0, 0]-S[1, 1])],
                [2*np.real(S[1, 0]), -2*np.real(S[0, 1]), -np.real(S[0, 0]-S[1, 1]), np.imag(S[0, 0]+S[1, 1])]])
print("The extinction matrix is: ")
Ke
# 值得注意的是，对比数值解和解析解时，特征值可以对比看是否相等，但特征向量不可对比，因为一个特征值对应特征向量不唯一
# 因此验证解析解时，看应看其是否可还原被分解矩阵

The extinction matrix is: 


array([[ 2.,  0.,  0., -0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0., -0., -0.,  2.]])

In [4]:
# 数值求解
eva, evec = np.linalg.eig(Ke)
print(eva)
print('-------数值解-----')
print(evec)

[2. 2. 2. 2.]
-------数值解-----
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# 验证数值解，下面的结果应该等于Ke
evec @ np.diag(eva) @ np.linalg.inv(evec)

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [7]:
# 解析求解
r = np.sqrt((S[0, 0] - S[1, 1])**2 + 4 * S[0, 1] * S[1, 0])
denom = (S[0, 0] - S[1, 1] + r)
if denom < 1e-20:
    b1 = 0.
    b2 = 0.
else:
    b1 = 2*S[1, 0] / denom
    b2 = -2*S[0, 1] / denom
# b1 = 2*S[1, 0] / (S[0, 0] - S[1, 1] + r)
# b2 = 2*S[0, 1] / (-S[0, 0] + S[1, 1] - r)

beta = np.array([r.imag, -1j*r.real, 1j*r.real, -r.imag]) + (S[0, 0] + S[1, 1]).imag
E = np.array([[1, np.conj(b2), b2, np.abs(b2)**2],
                [np.abs(b1)**2, b1, np.conj(b1), 1],
                [2*b1.real, 1+b1*np.conj(b2), 1+np.conj(b1)*b2, 2*np.real(b2)],
                [-2*b1.imag, -1j*(1-b1*np.conj(b2)), 1j*(1-np.conj(b1)*b2), 2*b2.imag]])

print(beta)
print('-------解析解-----')
print(E)

[2.+0.j 2.+0.j 2.+0.j 2.+0.j]
-------解析解-----
[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]
 [ 0.+0.j  1.+0.j  1.+0.j  0.+0.j]
 [-0.+0.j  0.-1.j  0.+1.j  0.+0.j]]


In [8]:
# 验证解析解
E @ np.diag(beta) @ np.linalg.inv(E)

array([[2.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 2.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 2.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 2.+0.j]])