In [1]:
import numpy as np

In [10]:
def my_fun(a,b=2, **kwargs):
    return a+b

In [11]:
para = {'a':11, 'b':3, 'c':4}

In [12]:
my_fun(**para)

14

In [5]:
S

{(2, 3): 2}

In [8]:
S['(2,3)']

KeyError: '(2,3)'

In [5]:
a

matlab.double([[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0]])

In [7]:
for x in a:
    print(x)

[0.0,0.0,0.0,0.0]
[0.0,0.0,0.0,0.0]
[0.0,0.0,0.0,0.0]
[0.0,0.0,0.0,0.0]


In [9]:
import numpy as np

In [10]:
b = np.array(a)

In [11]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
c = matlab.double([1, 1+2j], is_complex=True)

In [13]:
c

matlab.double([[(1+0j),(1+2j)]], is_complex=True)

In [1]:
a = (1,2,3)

In [2]:
x1,x2,x3=a

In [3]:
x1

1

In [4]:
import matlab.engine

In [5]:
eng = matlab.engine.start_matlab()

In [10]:
a=eng.sum(1+2j)

In [11]:
a

(1+2j)

In [13]:
type(a)

complex

In [15]:
eng.disp('fsdfsf', nargout=0)

In [16]:
import scipy

In [17]:
scipy.constants.speed_of_light

299792458.0

In [18]:
PI

NameError: name 'PI' is not defined

In [19]:
Pi

NameError: name 'Pi' is not defined

In [20]:
pi

NameError: name 'pi' is not defined

In [21]:
np.pi

NameError: name 'np' is not defined

In [23]:
import numpy as np

In [25]:
np.pi

3.141592653589793

In [26]:
import matlab.engine

In [27]:
eng = matlab.engine.start_matlab("-desktop")

In [28]:
eng.cd(r'E:/exps/lunar_scattering/lunar_regolith_scattering/mores/matlab', nargout=0)

In [37]:
eng.test_fun(matlab.double(1, is_complex=True), matlab.double(1+2j, is_complex=True), False)

ValueError: initializer must be a rectangular nested sequence

In [47]:
a = np.array(eng.test_fun(1.0, 1+2j, False))

In [48]:
a

array(nan)

In [49]:
np.isnan(a)

True

In [1]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2,3]])

In [3]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [6]:
f=np.array([1,2])#1*2
g=np.array([[1,2],
         [1,2],
         [1,2]])

In [7]:
g@f

array([5, 5, 5])

In [8]:
g

array([[1, 2],
       [1, 2],
       [1, 2]])

In [9]:
g.shape

(3, 2)

In [10]:
import numpy as np

In [11]:
np.pi

3.141592653589793

In [1]:
a = (1, 2, 3)

In [3]:
len(a)

3

In [1]:
a = (1, 2, 3)

In [2]:
type(a)

tuple

In [3]:
b = 2

In [4]:
type(b)

int

In [9]:
if type(a) == tuple:
    print('yes')
else:
    print('no')

yes


In [10]:
c = True
c is True

True

In [8]:
type(a)

tuple