In [1]:
def func():
    return 1,2,3

In [8]:
_,a,b=func()

In [11]:
b.shape

AttributeError: 'int' object has no attribute 'shape'

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [7]:
a = np.zeros((3,3))

In [4]:
b = a

In [5]:
b[0] = -5

In [6]:
a

array([-5,  2,  3])

In [27]:
a =np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b=a.view()

In [29]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b[0,0] = 0

In [31]:
a

array([[0, 2, 3],
       [4, 5, 6]])

In [32]:
b.reshape((3,2))

array([[0, 2],
       [3, 4],
       [5, 6]])

In [33]:
a

array([[0, 2, 3],
       [4, 5, 6]])

In [34]:
b[0,1] = 100

In [35]:
a

array([[  0, 100,   3],
       [  4,   5,   6]])