In [ ]:
import numpy as np
m = 1.77-0.63j
wavelength = 375
diameter = 30
radius = diameter/2
x = np.pi * diameter / wavelength
# epsr = np.conj(m**2)

In [8]:
from pytmatrix import tmatrix, tmatrix_aux
from pytmatrix.scatter import sca_xsect, ext_xsect, ssa
from pytmatrix.radar import radar_xsect
scatterer = tmatrix.Scatterer(radius=radius, wavelength=wavelength, m=np.conj(m), axis_ratio=1.0)

# A = np.pi * radius**2   # the geometry cross section of the sphere
cross_sections = {'Qext': ext_xsect(scatterer),
 'Qsca': sca_xsect(scatterer)}
scatterer.set_geometry(geom=tmatrix_aux.geom_vert_back)
Z = scatterer.get_Z()
S = scatterer.get_S()
sigma_back = radar_xsect(scatterer=scatterer)

print(f"S: {S}")
print(f"Z: {Z}")
print(f"sigma_back: {sigma_back}")
print(cross_sections)

S: [[-0.44997494-0.23563101j  0.        +0.j        ]
 [ 0.        +0.j          0.44997494+0.23563101j]]
Z: [[ 0.25799942  0.          0.         -0.        ]
 [ 0.          0.25799942  0.          0.        ]
 [ 0.          0.         -0.25799942  0.        ]
 [ 0.         -0.          0.         -0.25799942]]
sigma_back: 3.2421163439710985
{'Qext': np.float64(185.30076721146824), 'Qsca': 2.230493927260886}


In [6]:
import miepython

# qext, qsca, qback, g = miepython.mie(m,x)
qext, qsca, qback, g = miepython.efficiencies_mx(m,x)
geometric_cross_section = np.pi * radius**2
Csca  = qsca  * geometric_cross_section
# miepython.mie_phase_matrix(m=m, x=x, mu=0.5, norm='one') * Csca
Z_mie = miepython.phase_matrix(m=m, x=x, mu=-1, norm='qsca') * geometric_cross_section

In [11]:
cross_sections_mie = {'Qext': qext*geometric_cross_section,
 'Qsca': qsca*geometric_cross_section}

In [12]:
# print(f"S_mie: {S_mie}")
# print(f"S1^2, S2**2: {np.abs(np.array(S_mie))**2}")
# print(f"S1^2*C, S2**2*C: {np.abs(np.array(S_mie))**2 * sigma_s * 4 * np.pi}")
# print(f"abs(S1+S2)**2: {np.abs(np.array(S_mie).sum())**2 / (np.pi *x**2)}")
print(f"Z_mie: {Z_mie}")
# print(f"sigma_back_mie: {sigma_back_mie}")
print(f"cross_sections: {cross_sections_mie}")

Z_mie: [[ 0.25799943  0.          0.          0.        ]
 [ 0.          0.25799943  0.          0.        ]
 [ 0.          0.         -0.25799943 -0.        ]
 [ 0.          0.          0.         -0.25799943]]
cross_sections: {'Qext': np.float64(185.30077002773044), 'Qsca': np.float64(2.2304941115153163)}


In [ ]:
import PyMieScatt as ps

# ps.MieQ(m, wavelength=wavelength,diameter=diameter,asDict=True, asCrossSection=False)
cross_sections = ps.MieQ(m, wavelength=wavelength,diameter=diameter,asDict=True, asCrossSection=True)
sigma_back_mie = cross_sections['Cback']
sigma_s = cross_sections['Csca']
mu = 1 # 这才是后向散射？
k = 2*np.pi / wavelength
# C = 2*np.pi / (k**2 * sigma_s)
C = 2*np.pi / (k**2)
S_mie = ps.MieS1S2(m, x=np.pi*diameter/wavelength, mu=mu)
Z_mie = np.array(ps.MatrixElements(m, wavelength=wavelength,diameter=diameter, mu=mu))
print(f"S_mie: {S_mie}")
print(f"S1^2, S2**2: {np.abs(np.array(S_mie))**2}")
print(f"S1^2*C, S2**2*C: {np.abs(np.array(S_mie))**2 * sigma_s * 4 * np.pi}")
print(f"abs(S1+S2)**2: {np.abs(np.array(S_mie).sum())**2 / (np.pi *x**2)}")
print(f"Z_mie: {Z_mie}")
print(f"sigma_back_mie: {sigma_back_mie}")
print(f"cross_sections: {cross_sections}")

S_mie: ((2.9011038863556562e-05-0.0067616532769197765j), (2.9011038863556562e-05-0.0067616532769197765j))
S1^2, S2**2: [4.57207967e-05 4.57207967e-05]
S1^2*C, S2**2*C: [0.00075833 0.00075833]
abs(S1+S2)**2: 0.000921603655226708
Z_mie: [4.57207967e-05+0.j 0.00000000e+00+0.j 4.57207967e-05+0.j
 0.00000000e+00+0.j]
sigma_back_mie: 1.9148543377768608
cross_sections: {'Cext': 1.3198807928310954, 'Csca': 1.3198807928310958, 'Cabs': -4.598264133116849e-16, 'g': 0.01421824186369981, 'Cpr': 1.3011144084873711, 'Cback': 1.9148543377768608, 'Cratio': 1025.494710892755}


In [ ]:
(2-1j)/(3-2j)

(0.6153846153846154+0.07692307692307691j)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

import sys
sys.path.append('../../../')
%load_ext autoreload
%autoreload 2
from mores.layer.particle_utils import extinction_efficiency, scattering_efficiency, single_scattering_albedo

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


array([[ 1.13318490e+03,  6.48014975e-12, -1.77824547e-20,
        -1.50463277e-35],
       [ 6.48014975e-12,  1.13318490e+03, -4.13774011e-34,
         4.45290962e-20],
       [ 1.77824547e-20,  4.03241582e-34, -1.13318490e+03,
        -1.81898940e-11],
       [-1.20370622e-35,  4.45290962e-20,  1.81898940e-11,
        -1.13318490e+03]])

In [ ]:
{'Qext': extinction_efficiency(epsr, x),
 'Qsca': scattering_efficiency(epsr, x)}

{'Qext': 2.8584971868152085, 'Qsca': 1.3149275964079066}